"use strict"
import './js/htmlCollector';
import './styles.scss';
import './js/1initialHomePage';
import './js/2searchAndPlaginationHomePage';
import './js/3navigation';
import './js/4filmDetailsPage';
import './js/5libraryPage';
import './js/apiService';